name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  create_release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create_release.outputs.release_id }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: create release
        id: create_release
        run: |
          cd ./ci
          chmod +x create_release.sh
          ./create_release.sh ${{ secrets.PAT }} ${{ github.repository }} ${{ github.ref_name }}

  build_and_upload:
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.12"

      - name: build
        run: |
          cd ./ci
          chmod +x ./build.sh
          ./build.sh ${{ matrix.os }} ${{ matrix.arch }}

      - name: archive
        run: |
          cd ./ci
          chmod +x ./archive.sh
          ./archive.sh ${{ matrix.os }} ${{ matrix.arch }}

      - name: upload
        env:
          RELEASE_ID: ${{ needs.create_release.outputs.release_id }}
        run: |
          cd ./ci
          chmod +x ./upload.sh
          ./upload.sh ${{ secrets.PAT }} ${{ github.repository }} ${{ env.RELEASE_ID }} ${{ matrix.os }} ${{ matrix.arch }}
