name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.12"

      - name: Build
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o ./build/images-${{ matrix.os }}-${{ matrix.arch }}
          cp .env.example ./build/.env
          cp -r errors ./build/errors
          cp init.sql ./build/init.sql

      - name: Create tar archive
        run: |
          tar -czvf ./build/images-${{ matrix.os }}-${{ matrix.arch }}.tar.gz -C ./build images-${{ matrix.os }}-${{ matrix.arch }} .env errors init.sql

  create_release:
    runs-on: ubuntu-latest
    needs: build_and_release
    if: contains(github.ref, 'refs/tags/')
    steps:
      - name: Create Release
        id: create_release
        run: |
          response=$(curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d "{\"tag_name\": \"${GITHUB_REF_NAME}\", \"name\": \"Release ${GITHUB_REF_NAME}\", \"draft\": false, \"prerelease\": false}")
          echo "$response"
          RELEASE_ID=$(echo "$response" | jq -r '.id')
          echo "::set-output name=release_id::$RELEASE_ID"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

  upload_assets:
    runs-on: ubuntu-latest
    needs: [build_and_release, create_release]
    strategy:
      matrix:
        os: [linux, windows]
        arch: [amd64, arm64]
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Upload Release
        env:
          RELEASE_ID: ${{ needs.create_release.outputs.release_id }}
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @./build/images-${{ matrix.os }}-${{ matrix.arch }}.tar.gz \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.RELEASE_ID }}/assets?name=images-${{ matrix.os }}-${{ matrix.arch }}.tar.gz"
