name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, 386]
        include:
          - goos: linux
            goarch: amd64
            create_release: true
          - goos: linux
            goarch: 386
            create_release: false
          - goos: windows
            goarch: amd64
            create_release: false
          - goos: windows
            goarch: 386
            create_release: false
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21.12"

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build binary
        run: |
          mkdir -p build
          binary_name="myapp-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            binary_name="${binary_name}.exe"
          fi
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./build/${binary_name}
        env:
          CGO_ENABLED: 0

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}*

      - name: Download all artifacts
        if: matrix.create_release == 'true'
        uses: actions/download-artifact@v3
        with:
          path: ./build

      - name: Create Release
        if: matrix.create_release == 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Get Latest Release Upload URL
        if: matrix.create_release == 'true'
        id: get_upload_url
        run: |
          URL=$(curl -H "Authorization: token ${{ secrets.PAT }}" \
              https://api.github.com/repos/${{ github.repository }}/releases/latest \
              | jq -r '.upload_url' | sed -e "s/{?name,label}//")
          echo "UPLOAD_URL=${URL}" >> $GITHUB_ENV

      - name: Upload Release Asset
        if: ${{ always() }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: ./build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && matrix.goarch == '386' ? '.exe' : '' }}
          asset_name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && matrix.goarch == '386' ? '.exe' : '' }}
          asset_content_type: application/octet-stream
